project:
  type: website
  output-dir: _site

website:
  title: "Yekta's Dissertation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    title: "Contents"
    style: "docked"
    search: true
    tools:
      - icon: "github"
        href: "https://github.com/yektaLily/"
    background: light
    border: true
    width: 250px
    alignment: left  
    contents:  
      - text: "Home"
        href: "index.qmd" 
      - text: "Introduction"
        href: "introduction.qmd"
      - section: "Basics"
        contents:
          - text: "Technology Adoption"
            href: "techAdopt.qmd"
          - text: "Mobile Banking"
            href: "mobileBanking.qmd"
      - section: "Projects"
        contents:
        - section: "Project 1. SLR"
          href: "study1.qmd"
          contents: 
          - text: "Topic Modeling"
            href: "study1_tm.qmd"
          - text: "Theme Selection"
            href: "study1_theme.qmd"
          - text: "Data Analysis"
            href: "study1_DA.qmd"
        - section: "Project 2. Mental Health"
          href: "study2.qmd"
          contents:
          - text: "Data Analysis"
            href: "study2_DA.qmd"
        - section: "Project 3. Digital Divide"
          href: "study3.qmd"
          contents:
          - text: "Device Divide"
            href: "study3_DA.qmd"
format:
  html:
    theme:
      light: minty
      dark: darkly
    css: styles.css
    toc: true
    html-math-method: katex

margin-header: |
  ![](/images/uw-logo.png) 

